name: Release from Tag

on:
  push:
    tags:
      - "*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate distribution artifacts
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Release ${{ github.ref_name }}
            
            Compiled with Java 21.
          files: build/libs/*

      - name: URL to new release
        run: echo "Dependency Finder [${{ github.ref_name }}](${{ steps.create_release.outputs.url }})" >> $GITHUB_STEP_SUMMARY

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          ./gradlew dockerBuild
          docker image tag micronaut-depfind-test jeantessier/dependency-finder-micronaut:${{ github.ref_name }}
          docker image tag micronaut-depfind-test jeantessier/dependency-finder-micronaut:latest
          docker push jeantessier/dependency-finder-micronaut:${{ github.ref_name }}
          docker push jeantessier/dependency-finder-micronaut:latest
